name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # UTC time equates to at 1.00am FRI morning.
    - cron: 00 15 * * THU

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1
        with:
          merge_method: merge
          #  Time zone to use. Default is UTC.
          time_zone: "Australia/Melbourne"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
